#!/bin/bash
export GEMINI_API_KEY="AIzaSyDeAmn5Gh7e95JkaJmNmjWDWHuaLYXFO0w"
export HA_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI4ZTI3NTNhMGNiMGQ0ZTRhODM3NWVjYmU0YjdiOThmNyIsImlhdCI6MTc2ODcyNjUyMSwiZXhwIjoyMDg0MDg2NTIxfQ.0Ck6kFR6k6j72p1g20LnThgN2CO870O_xFFsskApItY"
#export SPOTIFY_CLIENT_ID=<your Spotify Client>
#export SPOTIFY_CLIENT_SECRET=<your Spotify Secret>

systemctl --user stop voiceassist
"$HOME/.venv/bin/python" -m voiceAssist.main
